DF_COLS = ['beds',
 'baths',
 'size_sqft',
 'pool',
 'balcony',
 'maid',
 'gym',
 'brand_new',
 'burj_view',
 'furnished',
 'sea_view',
 'beach',
 'location_Al Barari',
 'location_Al Barsha',
 'location_Al Furjan',
 'location_Al Jaddaf',
 'location_Al Mamzar',
 'location_Al Mizhar',
 'location_Al Quoz',
 'location_Al Qusais',
 'location_Al Rashidiya',
 'location_Al Safa',
 'location_Al Satwa',
 'location_Al Sufouh',
 'location_Al Warqaa',
 'location_Al Warsan',
 'location_Al Wasl',
 'location_Arabian Ranches',
 'location_Arabian Ranches 2',
 'location_Arabian Ranches 3',
 'location_Arjan',
 'location_Barsha Heights (Tecom)',
 'location_Bluewaters Island',
 'location_Bur Dubai',
 'location_Business Bay',
 'location_City of Arabia',
 'location_Culture Village',
 'location_DAMAC Hills',
 'location_DAMAC Hills 2 (Akoya by DAMAC)',
 'location_DIFC',
 'location_Damac Lagoons',
 'location_Deira',
 'location_Discovery Gardens',
 'location_Downtown Dubai',
 'location_Dubai Festival City',
 'location_Dubai Harbour',
 'location_Dubai Hills Estate',
 'location_Dubai Industrial Park',
 'location_Dubai Internet City',
 'location_Dubai Investment Park (DIP)',
 'location_Dubai Marina',
 'location_Dubai Maritime City',
 'location_Dubai Media City',
 'location_Dubai Production City (IMPZ)',
 'location_Dubai Residence Complex',
 'location_Dubai Science Park',
 'location_Dubai Silicon Oasis',
 'location_Dubai South',
 'location_Dubai Sports City',
 'location_Dubai Studio City',
 'location_Dubai Waterfront',
 'location_Dubai World Central',
 'location_Dubailand',
 'location_Emirates Hills',
 'location_Golf City',
 'location_Green Community',
 'location_International City',
 'location_Jebel Ali',
 'location_Jumeirah',
 'location_Jumeirah Beach Residence (JBR)',
 'location_Jumeirah Golf Estates',
 'location_Jumeirah Heights',
 'location_Jumeirah Islands',
 'location_Jumeirah Lake Towers (JLT)',
 'location_Jumeirah Park',
 'location_Jumeirah Village Circle (JVC)',
 'location_Jumeirah Village Triangle (JVT)',
 'location_Liwan',
 "location_Me'aisem 1",
 'location_Meydan City',
 'location_Mina Rashid',
 'location_Mirdif',
 'location_Mohammed Bin Rashid City',
 'location_Motor City',
 'location_Mudon',
 'location_Muhaisnah',
 'location_Nad Al Hamar',
 'location_Nad Al Sheba',
 'location_Palm Jumeirah',
 'location_Pearl Jumeirah',
 'location_Ras Al Khor',
 'location_Reem',
 'location_Remraam',
 'location_Serena',
 'location_Sheikh Zayed Road',
 'location_The Greens',
 'location_The Hills',
 'location_The Lagoons',
 'location_The Lakes',
 'location_The Meadows',
 'location_The Springs',
 'location_The Sustainable City',
 'location_The Valley',
 'location_The Views',
 'location_The Villa',
 'location_The World Islands',
 'location_Tilal Al Ghaf',
 'location_Town Square',
 'location_Umm Al Sheif',
 'location_Umm Suqeim',
 'location_Wadi Al Safa 2',
 'location_Wasl Gate',
 'location_World Trade Centre',
 "location_Za'abeel",
 'property_type_Apartment',
 'property_type_Hotel Apartment',
 'property_type_Penthouse',
 'property_type_Townhouse',
 'property_type_Villa']