LOCATIONS = ['Palm Jumeirah',
 'Dubai Marina',
 'Arjan',
 'Downtown Dubai',
 'Business Bay',
 'Jumeirah Village Circle (JVC)',
 'Dubai Hills Estate',
 'Jumeirah Beach Residence (JBR)',
 'Town Square',
 'Dubai Silicon Oasis',
 'The Lagoons',
 'DAMAC Hills',
 'Dubai Festival City',
 'Mirdif',
 'Dubai Harbour',
 'Bluewaters Island',
 'Meydan City',
 'Dubai Sports City',
 'Motor City',
 'Ras Al Khor',
 'Dubai Residence Complex',
 'Al Jaddaf',
 'Wasl Gate',
 'Dubailand',
 'International City',
 'Jumeirah',
 'Mohammed Bin Rashid City',
 'Jumeirah Lake Towers (JLT)',
 'Jumeirah Village Triangle (JVT)',
 'Al Wasl',
 'The World Islands',
 'Discovery Gardens',
 'Al Quoz',
 'Bur Dubai',
 'Dubai Production City (IMPZ)',
 'Culture Village',
 'Dubai Studio City',
 'World Trade Centre',
 'DIFC',
 'Green Community',
 'Muhaisnah',
 'Dubai South',
 'Dubai Media City',
 'Al Furjan',
 'The Views',
 'Umm Suqeim',
 'Barsha Heights (Tecom)',
 'The Greens',
 'Dubai Maritime City',
 'Al Barari',
 'Remraam',
 'Dubai Science Park',
 'City of Arabia',
 'Jebel Ali',
 "Za'abeel",
 'Jumeirah Golf Estates',
 'Dubai Investment Park (DIP)',
 'Al Sufouh',
 'Liwan',
 'Al Warsan',
 'Nad Al Sheba',
 'Dubai Internet City',
 'Mina Rashid',
 'Jumeirah Heights',
 'Dubai Waterfront',
 'DAMAC Hills 2 (Akoya by DAMAC)',
 'Deira',
 'Pearl Jumeirah',
 'The Hills',
 'Sheikh Zayed Road',
 'Mudon',
 'Al Mamzar',
 'Al Barsha',
 'Dubai World Central',
 'Dubai Industrial Park',
 'Wadi Al Safa 2',
 'The Valley',
 'Al Qusais',
 "Me'aisem 1",
 'Reem',
 'Jumeirah Park',
 'Serena',
 'Arabian Ranches 2',
 'Arabian Ranches',
 'The Springs',
 'Umm Al Sheif',
 'Damac Lagoons',
 'Tilal Al Ghaf',
 'The Lakes',
 'The Villa',
 'Arabian Ranches 3',
 'The Meadows',
 'Jumeirah Islands',
 'Emirates Hills',
 'Golf City',
 'The Sustainable City',
 'Al Safa',
 'Al Satwa',
 'Al Mizhar',
 'Al Warqaa',
 'Al Rashidiya',
 'Nad Al Hamar']